### ISSUE TITLE
Potential issue with Pathfinder 1e System?

### ISSUE THREAD

**Issue by MumboNT** [KayelGee/moar-folders#9]
I recently noticed that this module stopped functioning for me. I have tested that it's not a corrupted file or module conflict by redownloading the module files and running the module alone in a new instance.

I checked the console and noticed this:

commons.js:1703 
Error: You are accessing game.pf1, which will be restructured to match globalThis.pf1 in the future.
Please check whether directory and its contents are still available, or use globalThis.pf1 instead.
Deprecated since Version PF1 0.82.0
Backwards-compatible support will be removed in Version PF1 0.83.0
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Object.get (pf1.mjs:345:21)
    at MoarFolders.initialize (moar-folders.js:21:18)
    at Object.fn (moar-folders.js:85:38)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7952:11)
    at async Game._initializeGameView (foundry.js:8999:5)
    at async Game.initialize (foundry.js:7825:5)

I am running Foundry V10 Build 291 and Pathfinder 1 version 0.82.5.

**Comment by KayelGee** [comment]
can you try with the new version?

**Comment by MumboNT** [comment]
That seems to have fixed it.
